/* <internal>:0 */
 void chpl__init_ChapelStringLiterals(int64_t _ln, int32_t _fn) {
  c_string modFormatStr;
  c_string modStr;
  _ref_int32_t refIndentLevel = NULL;
  if (chpl__init_ChapelStringLiterals_p) {
    goto _exit_chpl__init_ChapelStringLiterals;
  }
  modFormatStr = "%*s\n";
  modStr = "ChapelStringLiterals";
  printModuleInit(modFormatStr, modStr, INT64(20));
  refIndentLevel = &moduleInitLevel;
  *(refIndentLevel) += INT64(1);
  chpl__init_ChapelStringLiterals_p = UINT8(true);
  *(refIndentLevel) -= INT64(1);
  _exit_chpl__init_ChapelStringLiterals:;
  return;
}

/* ChapelBase.chpl:37 */
void chpl__initStringLiterals(void) {
  c_ptr_uint8_t call_tmp = NULL;
  _ref_string ret_to_arg_ref_tmp_ = NULL;
  c_ptr_uint8_t call_tmp2 = NULL;
  _ref_string ret_to_arg_ref_tmp_2 = NULL;
  c_ptr_uint8_t call_tmp3 = NULL;
  _ref_string ret_to_arg_ref_tmp_3 = NULL;
  c_ptr_uint8_t call_tmp4 = NULL;
  _ref_string ret_to_arg_ref_tmp_4 = NULL;
  c_ptr_uint8_t call_tmp5 = NULL;
  _ref_string ret_to_arg_ref_tmp_5 = NULL;
  c_ptr_uint8_t call_tmp6 = NULL;
  _ref_string ret_to_arg_ref_tmp_6 = NULL;
  c_ptr_uint8_t call_tmp7 = NULL;
  _ref_string ret_to_arg_ref_tmp_7 = NULL;
  c_ptr_uint8_t call_tmp8 = NULL;
  _ref_string ret_to_arg_ref_tmp_8 = NULL;
  c_ptr_uint8_t call_tmp9 = NULL;
  _ref_string ret_to_arg_ref_tmp_9 = NULL;
  c_ptr_uint8_t call_tmp10 = NULL;
  _ref_string ret_to_arg_ref_tmp_10 = NULL;
  c_ptr_uint8_t call_tmp11 = NULL;
  _ref_string ret_to_arg_ref_tmp_11 = NULL;
  c_ptr_uint8_t call_tmp12 = NULL;
  _ref_string ret_to_arg_ref_tmp_12 = NULL;
  c_ptr_uint8_t call_tmp13 = NULL;
  _ref_string ret_to_arg_ref_tmp_13 = NULL;
  c_ptr_uint8_t call_tmp14 = NULL;
  _ref_string ret_to_arg_ref_tmp_14 = NULL;
  c_ptr_uint8_t call_tmp15 = NULL;
  _ref_string ret_to_arg_ref_tmp_15 = NULL;
  c_ptr_uint8_t call_tmp16 = NULL;
  _ref_string ret_to_arg_ref_tmp_16 = NULL;
  c_ptr_uint8_t call_tmp17 = NULL;
  _ref_string ret_to_arg_ref_tmp_17 = NULL;
  c_ptr_uint8_t call_tmp18 = NULL;
  _ref_string ret_to_arg_ref_tmp_18 = NULL;
  c_ptr_uint8_t call_tmp19 = NULL;
  _ref_string ret_to_arg_ref_tmp_19 = NULL;
  c_ptr_uint8_t call_tmp20 = NULL;
  _ref_string ret_to_arg_ref_tmp_20 = NULL;
  c_ptr_uint8_t call_tmp21 = NULL;
  _ref_string ret_to_arg_ref_tmp_21 = NULL;
  c_ptr_uint8_t call_tmp22 = NULL;
  _ref_string ret_to_arg_ref_tmp_22 = NULL;
  c_ptr_uint8_t call_tmp23 = NULL;
  _ref_string ret_to_arg_ref_tmp_23 = NULL;
  c_ptr_uint8_t call_tmp24 = NULL;
  _ref_string ret_to_arg_ref_tmp_24 = NULL;
  c_ptr_uint8_t call_tmp25 = NULL;
  _ref_string ret_to_arg_ref_tmp_25 = NULL;
  c_ptr_uint8_t call_tmp26 = NULL;
  _ref_string ret_to_arg_ref_tmp_26 = NULL;
  c_ptr_uint8_t call_tmp27 = NULL;
  _ref_string ret_to_arg_ref_tmp_27 = NULL;
  c_ptr_uint8_t call_tmp28 = NULL;
  _ref_string ret_to_arg_ref_tmp_28 = NULL;
  c_ptr_uint8_t call_tmp29 = NULL;
  _ref_string ret_to_arg_ref_tmp_29 = NULL;
  c_ptr_uint8_t call_tmp30 = NULL;
  _ref_string ret_to_arg_ref_tmp_30 = NULL;
  c_ptr_uint8_t call_tmp31 = NULL;
  _ref_string ret_to_arg_ref_tmp_31 = NULL;
  c_ptr_uint8_t call_tmp32 = NULL;
  _ref_string ret_to_arg_ref_tmp_32 = NULL;
  c_ptr_uint8_t call_tmp33 = NULL;
  _ref_string ret_to_arg_ref_tmp_33 = NULL;
  c_ptr_uint8_t call_tmp34 = NULL;
  _ref_string ret_to_arg_ref_tmp_34 = NULL;
  c_ptr_uint8_t call_tmp35 = NULL;
  _ref_string ret_to_arg_ref_tmp_35 = NULL;
  c_ptr_uint8_t call_tmp36 = NULL;
  _ref_string ret_to_arg_ref_tmp_36 = NULL;
  c_ptr_uint8_t call_tmp37 = NULL;
  _ref_string ret_to_arg_ref_tmp_37 = NULL;
  c_ptr_uint8_t call_tmp38 = NULL;
  _ref_string ret_to_arg_ref_tmp_38 = NULL;
  c_ptr_uint8_t call_tmp39 = NULL;
  _ref_string ret_to_arg_ref_tmp_39 = NULL;
  c_ptr_uint8_t call_tmp40 = NULL;
  _ref_string ret_to_arg_ref_tmp_40 = NULL;
  c_ptr_uint8_t call_tmp41 = NULL;
  _ref_string ret_to_arg_ref_tmp_41 = NULL;
  c_ptr_uint8_t call_tmp42 = NULL;
  _ref_string ret_to_arg_ref_tmp_42 = NULL;
  c_ptr_uint8_t call_tmp43 = NULL;
  _ref_string ret_to_arg_ref_tmp_43 = NULL;
  c_ptr_uint8_t call_tmp44 = NULL;
  _ref_string ret_to_arg_ref_tmp_44 = NULL;
  c_ptr_uint8_t call_tmp45 = NULL;
  _ref_string ret_to_arg_ref_tmp_45 = NULL;
  c_ptr_uint8_t call_tmp46 = NULL;
  _ref_string ret_to_arg_ref_tmp_46 = NULL;
  c_ptr_uint8_t call_tmp47 = NULL;
  _ref_string ret_to_arg_ref_tmp_47 = NULL;
  c_ptr_uint8_t call_tmp48 = NULL;
  _ref_string ret_to_arg_ref_tmp_48 = NULL;
  c_ptr_uint8_t call_tmp49 = NULL;
  _ref_string ret_to_arg_ref_tmp_49 = NULL;
  c_ptr_uint8_t call_tmp50 = NULL;
  _ref_string ret_to_arg_ref_tmp_50 = NULL;
  c_ptr_uint8_t call_tmp51 = NULL;
  _ref_string ret_to_arg_ref_tmp_51 = NULL;
  c_ptr_uint8_t call_tmp52 = NULL;
  _ref_string ret_to_arg_ref_tmp_52 = NULL;
  c_ptr_uint8_t call_tmp53 = NULL;
  _ref_string ret_to_arg_ref_tmp_53 = NULL;
  c_ptr_uint8_t call_tmp54 = NULL;
  _ref_string ret_to_arg_ref_tmp_54 = NULL;
  c_ptr_uint8_t call_tmp55 = NULL;
  _ref_string ret_to_arg_ref_tmp_55 = NULL;
  c_ptr_uint8_t call_tmp56 = NULL;
  _ref_string ret_to_arg_ref_tmp_56 = NULL;
  c_ptr_uint8_t call_tmp57 = NULL;
  _ref_string ret_to_arg_ref_tmp_57 = NULL;
  c_ptr_uint8_t call_tmp58 = NULL;
  _ref_string ret_to_arg_ref_tmp_58 = NULL;
  call_tmp = ((c_ptr_uint8_t)("Pure virtual function called."));
  ret_to_arg_ref_tmp_ = &_str_literal_32;
  string4(call_tmp, INT64(29), INT64(30), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_);
  call_tmp2 = ((c_ptr_uint8_t)("Cannot call .c_str() on a remote string"));
  ret_to_arg_ref_tmp_2 = &_str_literal_306;
  string4(call_tmp2, INT64(39), INT64(40), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_2);
  call_tmp3 = ((c_ptr_uint8_t)("range out of bounds of string"));
  ret_to_arg_ref_tmp_3 = &_str_literal_311;
  string4(call_tmp3, INT64(29), INT64(30), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_3);
  call_tmp4 = ((c_ptr_uint8_t)(""));
  ret_to_arg_ref_tmp_4 = &_str_literal_318;
  string4(call_tmp4, INT64(0), INT64(0), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_4);
  call_tmp5 = ((c_ptr_uint8_t)(" \t\r\n"));
  ret_to_arg_ref_tmp_5 = &_str_literal_339;
  string4(call_tmp5, INT64(4), INT64(5), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_5);
  call_tmp6 = ((c_ptr_uint8_t)(""));
  ret_to_arg_ref_tmp_6 = &_str_literal_341;
  string4(call_tmp6, INT64(0), INT64(0), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_6);
  call_tmp7 = ((c_ptr_uint8_t)("a"));
  ret_to_arg_ref_tmp_7 = &_str_literal_367;
  string4(call_tmp7, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_7);
  call_tmp8 = ((c_ptr_uint8_t)(" "));
  ret_to_arg_ref_tmp_8 = &_str_literal_375;
  string4(call_tmp8, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_8);
  call_tmp9 = ((c_ptr_uint8_t)(")"));
  ret_to_arg_ref_tmp_9 = &_str_literal_387;
  string4(call_tmp9, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_9);
  call_tmp10 = ((c_ptr_uint8_t)("tuple access out of bounds: "));
  ret_to_arg_ref_tmp_10 = &_str_literal_510;
  string4(call_tmp10, INT64(28), INT64(29), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_10);
  call_tmp11 = ((c_ptr_uint8_t)("true"));
  ret_to_arg_ref_tmp_11 = &_str_literal_520;
  string4(call_tmp11, INT64(4), INT64(5), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_11);
  call_tmp12 = ((c_ptr_uint8_t)(", "));
  ret_to_arg_ref_tmp_12 = &_str_literal_537;
  string4(call_tmp12, INT64(2), INT64(3), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_12);
  call_tmp13 = ((c_ptr_uint8_t)("("));
  ret_to_arg_ref_tmp_13 = &_str_literal_541;
  string4(call_tmp13, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_13);
  call_tmp14 = ((c_ptr_uint8_t)("With a negative count, the range must have a last index."));
  ret_to_arg_ref_tmp_14 = &_str_literal_680;
  string4(call_tmp14, INT64(56), INT64(57), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_14);
  call_tmp15 = ((c_ptr_uint8_t)("Iteration over a bounded range may be incorrect due to overflow."));
  ret_to_arg_ref_tmp_15 = &_str_literal_694;
  string4(call_tmp15, INT64(64), INT64(65), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_15);
  call_tmp16 = ((c_ptr_uint8_t)("'"));
  ret_to_arg_ref_tmp_16 = &_str_literal_806;
  string4(call_tmp16, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_16);
  call_tmp17 = ((c_ptr_uint8_t)("Cannot create additional LocaleModel instances"));
  ret_to_arg_ref_tmp_17 = &_str_literal_859;
  string4(call_tmp17, INT64(46), INT64(47), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_17);
  call_tmp18 = ((c_ptr_uint8_t)("requesting a child from a LocaleModel locale"));
  ret_to_arg_ref_tmp_18 = &_str_literal_863;
  string4(call_tmp18, INT64(44), INT64(45), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_18);
  call_tmp19 = ((c_ptr_uint8_t)("dataParTasksPerLocale must be >= 0"));
  ret_to_arg_ref_tmp_19 = &_str_literal_906;
  string4(call_tmp19, INT64(34), INT64(35), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_19);
  call_tmp20 = ((c_ptr_uint8_t)("dataParMinGranularity must be > 0"));
  ret_to_arg_ref_tmp_20 = &_str_literal_908;
  string4(call_tmp20, INT64(33), INT64(34), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_20);
  call_tmp21 = ((c_ptr_uint8_t)("array index out of bounds: "));
  ret_to_arg_ref_tmp_21 = &_str_literal_987;
  string4(call_tmp21, INT64(27), INT64(28), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_21);
  call_tmp22 = ((c_ptr_uint8_t)("distribution reference count is negative!"));
  ret_to_arg_ref_tmp_22 = &_str_literal_1483;
  string4(call_tmp22, INT64(41), INT64(42), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_22);
  call_tmp23 = ((c_ptr_uint8_t)("internal error: dsiMyDist is not implemented"));
  ret_to_arg_ref_tmp_23 = &_str_literal_1485;
  string4(call_tmp23, INT64(44), INT64(45), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_23);
  call_tmp24 = ((c_ptr_uint8_t)("domain reference count is negative!"));
  ret_to_arg_ref_tmp_24 = &_str_literal_1491;
  string4(call_tmp24, INT64(35), INT64(36), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_24);
  call_tmp25 = ((c_ptr_uint8_t)("internal error: dsiGetBaseDom is not implemented"));
  ret_to_arg_ref_tmp_25 = &_str_literal_1497;
  string4(call_tmp25, INT64(48), INT64(49), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_25);
  call_tmp26 = ((c_ptr_uint8_t)("reallocating not supported for this array type"));
  ret_to_arg_ref_tmp_26 = &_str_literal_1500;
  string4(call_tmp26, INT64(46), INT64(47), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_26);
  call_tmp27 = ((c_ptr_uint8_t)("array reference count is negative!"));
  ret_to_arg_ref_tmp_27 = &_str_literal_1520;
  string4(call_tmp27, INT64(34), INT64(35), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_27);
  call_tmp28 = ((c_ptr_uint8_t)(":"));
  ret_to_arg_ref_tmp_28 = &_str_literal_1548;
  string4(call_tmp28, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_28);
  call_tmp29 = ((c_ptr_uint8_t)("halt reached - "));
  ret_to_arg_ref_tmp_29 = &_str_literal_1551;
  string4(call_tmp29, INT64(15), INT64(16), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_29);
  call_tmp30 = ((c_ptr_uint8_t)("To use task tracking, you must recompile with --task-tracking"));
  ret_to_arg_ref_tmp_30 = &_str_literal_1749;
  string4(call_tmp30, INT64(61), INT64(62), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_30);
  call_tmp31 = ((c_ptr_uint8_t)("false"));
  ret_to_arg_ref_tmp_31 = &_str_literal_1752;
  string4(call_tmp31, INT64(5), INT64(6), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_31);
  call_tmp32 = ((c_ptr_uint8_t)("Unexpected value when converting from string to bool: '"));
  ret_to_arg_ref_tmp_32 = &_str_literal_1754;
  string4(call_tmp32, INT64(55), INT64(56), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_32);
  call_tmp33 = ((c_ptr_uint8_t)("Hello, world!"));
  ret_to_arg_ref_tmp_33 = &_str_literal_1760;
  string4(call_tmp33, INT64(13), INT64(14), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_33);
  call_tmp34 = ((c_ptr_uint8_t)("Operation attempted on an invalid file"));
  ret_to_arg_ref_tmp_34 = &_str_literal_1890;
  string4(call_tmp34, INT64(38), INT64(39), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_34);
  call_tmp35 = ((c_ptr_uint8_t)("unknown"));
  ret_to_arg_ref_tmp_35 = &_str_literal_1899;
  string4(call_tmp35, INT64(7), INT64(8), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_35);
  call_tmp36 = ((c_ptr_uint8_t)("r"));
  ret_to_arg_ref_tmp_36 = &_str_literal_1906;
  string4(call_tmp36, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_36);
  call_tmp37 = ((c_ptr_uint8_t)("r+"));
  ret_to_arg_ref_tmp_37 = &_str_literal_1908;
  string4(call_tmp37, INT64(2), INT64(3), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_37);
  call_tmp38 = ((c_ptr_uint8_t)("w"));
  ret_to_arg_ref_tmp_38 = &_str_literal_1910;
  string4(call_tmp38, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_38);
  call_tmp39 = ((c_ptr_uint8_t)("w+"));
  ret_to_arg_ref_tmp_39 = &_str_literal_1912;
  string4(call_tmp39, INT64(2), INT64(3), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_39);
  call_tmp40 = ((c_ptr_uint8_t)("in openfd"));
  ret_to_arg_ref_tmp_40 = &_str_literal_1968;
  string4(call_tmp40, INT64(9), INT64(10), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_40);
  call_tmp41 = ((c_ptr_uint8_t)("in openfp"));
  ret_to_arg_ref_tmp_41 = &_str_literal_1970;
  string4(call_tmp41, INT64(9), INT64(10), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_41);
  call_tmp42 = ((c_ptr_uint8_t)("in lock"));
  ret_to_arg_ref_tmp_42 = &_str_literal_1988;
  string4(call_tmp42, INT64(7), INT64(8), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_42);
  call_tmp43 = ((c_ptr_uint8_t)("in file.reader"));
  ret_to_arg_ref_tmp_43 = &_str_literal_2015;
  string4(call_tmp43, INT64(14), INT64(15), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_43);
  call_tmp44 = ((c_ptr_uint8_t)("in file.writer"));
  ret_to_arg_ref_tmp_44 = &_str_literal_2022;
  string4(call_tmp44, INT64(14), INT64(15), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_44);
  call_tmp45 = ((c_ptr_uint8_t)(""));
  ret_to_arg_ref_tmp_45 = &_str_literal_2058;
  string4(call_tmp45, INT64(0), INT64(0), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_45);
  call_tmp46 = ((c_ptr_uint8_t)("b"));
  ret_to_arg_ref_tmp_46 = &_str_literal_2061;
  string4(call_tmp46, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_46);
  call_tmp47 = ((c_ptr_uint8_t)("c"));
  ret_to_arg_ref_tmp_47 = &_str_literal_2063;
  string4(call_tmp47, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_47);
  call_tmp48 = ((c_ptr_uint8_t)("d"));
  ret_to_arg_ref_tmp_48 = &_str_literal_2065;
  string4(call_tmp48, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_48);
  call_tmp49 = ((c_ptr_uint8_t)("e"));
  ret_to_arg_ref_tmp_49 = &_str_literal_2067;
  string4(call_tmp49, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_49);
  call_tmp50 = ((c_ptr_uint8_t)("f"));
  ret_to_arg_ref_tmp_50 = &_str_literal_2069;
  string4(call_tmp50, INT64(1), INT64(2), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_50);
  call_tmp51 = ((c_ptr_uint8_t)("in channel.write("));
  ret_to_arg_ref_tmp_51 = &_str_literal_2109;
  string4(call_tmp51, INT64(17), INT64(18), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_51);
  call_tmp52 = ((c_ptr_uint8_t)(""));
  ret_to_arg_ref_tmp_52 = &_str_literal_2111;
  string4(call_tmp52, INT64(0), INT64(0), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_52);
  call_tmp53 = ((c_ptr_uint8_t)(" with path "));
  ret_to_arg_ref_tmp_53 = &_str_literal_2329;
  string4(call_tmp53, INT64(11), INT64(12), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_53);
  call_tmp54 = ((c_ptr_uint8_t)(" offset "));
  ret_to_arg_ref_tmp_54 = &_str_literal_2331;
  string4(call_tmp54, INT64(8), INT64(9), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_54);
  call_tmp55 = ((c_ptr_uint8_t)("casting int(64) less than 0 to uint(64)"));
  ret_to_arg_ref_tmp_55 = &_str_literal_2657;
  string4(call_tmp55, INT64(39), INT64(40), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_55);
  call_tmp56 = ((c_ptr_uint8_t)("casting uint(64) with a value greater than the maximum of int(64) to int(64)"));
  ret_to_arg_ref_tmp_56 = &_str_literal_2668;
  string4(call_tmp56, INT64(76), INT64(77), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_56);
  call_tmp57 = ((c_ptr_uint8_t)("string"));
  ret_to_arg_ref_tmp_57 = &_str_literal_2711;
  string4(call_tmp57, INT64(6), INT64(7), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_57);
  call_tmp58 = ((c_ptr_uint8_t)("ioNewline"));
  ret_to_arg_ref_tmp_58 = &_str_literal_2713;
  string4(call_tmp58, INT64(9), INT64(10), UINT8(false), UINT8(false), ret_to_arg_ref_tmp_58);
  return;
}

