/* Error.chpl:38 */
 void chpl__init_Error(int64_t _ln_chpl, int32_t _fn_chpl) {
  c_string modFormatStr_chpl;
  c_string modStr_chpl;
  _ref_int32_t refIndentLevel_chpl = NULL;
  if (chpl__init_Error_p) {
    goto _exit_chpl__init_Error_chpl;
  }
  modFormatStr_chpl = "%*s\n";
  modStr_chpl = "Error";
  printModuleInit(modFormatStr_chpl, modStr_chpl, INT64(5));
  refIndentLevel_chpl = &moduleInitLevel;
  *(refIndentLevel_chpl) += INT64(1);
  chpl__init_Error_p = UINT8(true);
  {
    chpl__init_SysBasic(INT64(38), INT32(55));
  }
  *(refIndentLevel_chpl) -= INT64(1);
  _exit_chpl__init_Error_chpl:;
  return;
}

/* Error.chpl:49 */
 c_string quote_string_chpl(string* const s_chpl, int64_t len_chpl) {
  c_void_ptr local_c_nil_chpl;
  string local__str_literal_306_chpl;
  c_string ret_chpl;
  c_string ret_chpl2;
  string call_tmp_chpl;
  string call_tmp_chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl3;
  c_ptr_uint8_t coerce_tmp_chpl2 = NULL;
  c_string call_tmp_chpl4;
  syserr call_tmp_chpl5;
  _ref_c_string _ref_tmp__chpl = NULL;
  int32_t call_tmp_chpl6;
  chpl_bool call_tmp_chpl7;
  c_string call_tmp_chpl8;
  _ref_string _ref_tmp__chpl2 = NULL;
  _ref_string _ref_tmp__chpl3 = NULL;
  local_c_nil_chpl = c_nil;
  local__str_literal_306_chpl = _str_literal_306;
  ret_chpl2 = "";
  ret_to_arg_ref_tmp__chpl = &call_tmp_chpl2;
  string2(s_chpl, UINT8(false), ret_to_arg_ref_tmp__chpl);
  call_tmp_chpl = call_tmp_chpl2;
  coerce_tmp_chpl = (&call_tmp_chpl)->locale_id;
  call_tmp_chpl3 = (coerce_tmp_chpl != chpl_nodeID);
  if (call_tmp_chpl3) {
    halt(&local__str_literal_306_chpl, INT64(60), INT32(55));
  }
  coerce_tmp_chpl2 = (&call_tmp_chpl)->buff;
  call_tmp_chpl4 = ((c_string)(coerce_tmp_chpl2));
  _ref_tmp__chpl = &ret_chpl2;
  call_tmp_chpl5 = qio_quote_string(UINT8(34), UINT8(34), QIO_STRING_FORMAT_CHPL, call_tmp_chpl4, len_chpl, _ref_tmp__chpl, local_c_nil_chpl);
  call_tmp_chpl6 = qio_err_iserr(call_tmp_chpl5);
  call_tmp_chpl7 = (call_tmp_chpl6 != INT32(0));
  if (call_tmp_chpl7) {
    call_tmp_chpl8 = qio_strdup("<error>");
    ret_chpl = call_tmp_chpl8;
    _ref_tmp__chpl2 = &call_tmp_chpl;
    chpl___TILDE_string(_ref_tmp__chpl2);
    goto _end_quote_string_chpl;
  }
  ret_chpl = ret_chpl2;
  _ref_tmp__chpl3 = &call_tmp_chpl;
  chpl___TILDE_string(_ref_tmp__chpl3);
  _end_quote_string_chpl:;
  return ret_chpl;
}

/* Error.chpl:97 */
 void ioerror_chpl(syserr error_chpl, string* const msg_chpl, string* const path_chpl) {
  string local__str_literal_306_chpl;
  string local__str_literal_2329_chpl;
  string local__str_literal_375_chpl;
  int32_t call_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  int32_t strerror_err_chpl;
  string errstr_chpl;
  c_string call_tmp_chpl3;
  _ref_int32_t _ref_tmp__chpl = NULL;
  string call_tmp_chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  string quotedpath_chpl;
  int64_t ret_chpl;
  c_string call_tmp_chpl5;
  string call_tmp_chpl6;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  string err_msg_chpl;
  string type_tmp_chpl;
  string this_chpl;
  c_ptr_uint8_t call_tmp_chpl7 = NULL;
  int32_t default_arglocale_id_chpl;
  string wrap_call_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl3 = NULL;
  string call_tmp_chpl8;
  string _autoCopy_tmp__chpl;
  _ref_string ret_to_arg_ref_tmp__chpl4 = NULL;
  string call_tmp_chpl9;
  string _autoCopy_tmp__chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl5 = NULL;
  string call_tmp_chpl10;
  string _autoCopy_tmp__chpl3;
  _ref_string ret_to_arg_ref_tmp__chpl6 = NULL;
  string call_tmp_chpl11;
  string _autoCopy_tmp__chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl7 = NULL;
  _ref_string _ref_tmp__chpl2 = NULL;
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl12;
  c_ptr_uint8_t coerce_tmp_chpl2 = NULL;
  c_string call_tmp_chpl13;
  _ref_string _ref_tmp__chpl3 = NULL;
  _ref_string _ref_tmp__chpl4 = NULL;
  _ref_string _ref_tmp__chpl5 = NULL;
  _ref_string _ref_tmp__chpl6 = NULL;
  _ref_string _ref_tmp__chpl7 = NULL;
  _ref_string _ref_tmp__chpl8 = NULL;
  _ref_string _ref_tmp__chpl9 = NULL;
  local__str_literal_306_chpl = _str_literal_306;
  local__str_literal_2329_chpl = _str_literal_2329;
  local__str_literal_375_chpl = _str_literal_375;
  call_tmp_chpl = qio_err_iserr(error_chpl);
  call_tmp_chpl2 = (call_tmp_chpl != INT32(0));
  if (call_tmp_chpl2) {
    strerror_err_chpl = INT32(0);
    _ref_tmp__chpl = &strerror_err_chpl;
    call_tmp_chpl3 = sys_strerror_syserr_str(error_chpl, _ref_tmp__chpl);
    ret_to_arg_ref_tmp__chpl = &call_tmp_chpl4;
    _cast(call_tmp_chpl3, ret_to_arg_ref_tmp__chpl);
    errstr_chpl = call_tmp_chpl4;
    ret_chpl = (path_chpl)->len;
    call_tmp_chpl5 = quote_string_chpl(path_chpl, ret_chpl);
    ret_to_arg_ref_tmp__chpl2 = &call_tmp_chpl6;
    _cast(call_tmp_chpl5, ret_to_arg_ref_tmp__chpl2);
    quotedpath_chpl = call_tmp_chpl6;
    (&this_chpl)->len = INT64(0);
    (&this_chpl)->_size = INT64(0);
    (&this_chpl)->buff = nil;
    (&this_chpl)->owned = UINT8(false);
    (&this_chpl)->locale_id = INT32(0);
    (&this_chpl)->len = INT64(0);
    (&this_chpl)->_size = INT64(0);
    call_tmp_chpl7 = ((c_ptr_uint8_t)(nil));
    (&this_chpl)->buff = call_tmp_chpl7;
    (&this_chpl)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl3 = &wrap_call_tmp_chpl;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl7, UINT8(true), default_arglocale_id_chpl, &this_chpl, ret_to_arg_ref_tmp__chpl3);
    type_tmp_chpl = wrap_call_tmp_chpl;
    ret_to_arg_ref_tmp__chpl4 = &_autoCopy_tmp__chpl;
    chpl___PLUS_(&call_tmp_chpl4, &local__str_literal_375_chpl, ret_to_arg_ref_tmp__chpl4);
    call_tmp_chpl8 = _autoCopy_tmp__chpl;
    ret_to_arg_ref_tmp__chpl5 = &_autoCopy_tmp__chpl2;
    chpl___PLUS_(&_autoCopy_tmp__chpl, msg_chpl, ret_to_arg_ref_tmp__chpl5);
    call_tmp_chpl9 = _autoCopy_tmp__chpl2;
    ret_to_arg_ref_tmp__chpl6 = &_autoCopy_tmp__chpl3;
    chpl___PLUS_(&_autoCopy_tmp__chpl2, &local__str_literal_2329_chpl, ret_to_arg_ref_tmp__chpl6);
    call_tmp_chpl10 = _autoCopy_tmp__chpl3;
    ret_to_arg_ref_tmp__chpl7 = &_autoCopy_tmp__chpl4;
    chpl___PLUS_(&_autoCopy_tmp__chpl3, &call_tmp_chpl6, ret_to_arg_ref_tmp__chpl7);
    call_tmp_chpl11 = _autoCopy_tmp__chpl4;
    _ref_tmp__chpl2 = &type_tmp_chpl;
    chpl___ASSIGN_2(_ref_tmp__chpl2, &_autoCopy_tmp__chpl4);
    err_msg_chpl = type_tmp_chpl;
    coerce_tmp_chpl = (&err_msg_chpl)->locale_id;
    call_tmp_chpl12 = (coerce_tmp_chpl != chpl_nodeID);
    if (call_tmp_chpl12) {
      halt(&local__str_literal_306_chpl, INT64(104), INT32(55));
    }
    coerce_tmp_chpl2 = (&err_msg_chpl)->buff;
    call_tmp_chpl13 = ((c_string)(coerce_tmp_chpl2));
    chpl_error(call_tmp_chpl13, INT64(104), INT32(55));
    _ref_tmp__chpl3 = &errstr_chpl;
    chpl___TILDE_string(_ref_tmp__chpl3);
    _ref_tmp__chpl4 = &quotedpath_chpl;
    chpl___TILDE_string(_ref_tmp__chpl4);
    _ref_tmp__chpl5 = &err_msg_chpl;
    chpl___TILDE_string(_ref_tmp__chpl5);
    _ref_tmp__chpl6 = &call_tmp_chpl8;
    chpl___TILDE_string(_ref_tmp__chpl6);
    _ref_tmp__chpl7 = &call_tmp_chpl9;
    chpl___TILDE_string(_ref_tmp__chpl7);
    _ref_tmp__chpl8 = &call_tmp_chpl10;
    chpl___TILDE_string(_ref_tmp__chpl8);
    _ref_tmp__chpl9 = &call_tmp_chpl11;
    chpl___TILDE_string(_ref_tmp__chpl9);
  }
  return;
}

/* Error.chpl:119 */
 void ioerror_chpl2(syserr error_chpl, string* const msg_chpl, string* const path_chpl, int64_t offset_chpl) {
  string local__str_literal_306_chpl;
  string local__str_literal_2331_chpl;
  string local__str_literal_2329_chpl;
  string local__str_literal_375_chpl;
  int32_t call_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  int32_t strerror_err_chpl;
  string errstr_chpl;
  c_string call_tmp_chpl3;
  _ref_int32_t _ref_tmp__chpl = NULL;
  string call_tmp_chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  string quotedpath_chpl;
  int64_t ret_chpl;
  c_string call_tmp_chpl5;
  string call_tmp_chpl6;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  string err_msg_chpl;
  string type_tmp_chpl;
  string this_chpl;
  c_ptr_uint8_t call_tmp_chpl7 = NULL;
  int32_t default_arglocale_id_chpl;
  string wrap_call_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl3 = NULL;
  string call_tmp_chpl8;
  string _autoCopy_tmp__chpl;
  _ref_string ret_to_arg_ref_tmp__chpl4 = NULL;
  string call_tmp_chpl9;
  string _autoCopy_tmp__chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl5 = NULL;
  string call_tmp_chpl10;
  string _autoCopy_tmp__chpl3;
  _ref_string ret_to_arg_ref_tmp__chpl6 = NULL;
  string call_tmp_chpl11;
  string _autoCopy_tmp__chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl7 = NULL;
  string call_tmp_chpl12;
  string _autoCopy_tmp__chpl5;
  _ref_string ret_to_arg_ref_tmp__chpl8 = NULL;
  string call_tmp_chpl13;
  string _autoCopy_tmp__chpl6;
  _ref_string ret_to_arg_ref_tmp__chpl9 = NULL;
  string call_tmp_chpl14;
  string _autoCopy_tmp__chpl7;
  _ref_string ret_to_arg_ref_tmp__chpl10 = NULL;
  _ref_string _ref_tmp__chpl2 = NULL;
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl15;
  c_ptr_uint8_t coerce_tmp_chpl2 = NULL;
  c_string call_tmp_chpl16;
  _ref_string _ref_tmp__chpl3 = NULL;
  _ref_string _ref_tmp__chpl4 = NULL;
  _ref_string _ref_tmp__chpl5 = NULL;
  _ref_string _ref_tmp__chpl6 = NULL;
  _ref_string _ref_tmp__chpl7 = NULL;
  _ref_string _ref_tmp__chpl8 = NULL;
  _ref_string _ref_tmp__chpl9 = NULL;
  _ref_string _ref_tmp__chpl10 = NULL;
  _ref_string _ref_tmp__chpl11 = NULL;
  _ref_string _ref_tmp__chpl12 = NULL;
  local__str_literal_306_chpl = _str_literal_306;
  local__str_literal_2331_chpl = _str_literal_2331;
  local__str_literal_2329_chpl = _str_literal_2329;
  local__str_literal_375_chpl = _str_literal_375;
  call_tmp_chpl = qio_err_iserr(error_chpl);
  call_tmp_chpl2 = (call_tmp_chpl != INT32(0));
  if (call_tmp_chpl2) {
    strerror_err_chpl = INT32(0);
    _ref_tmp__chpl = &strerror_err_chpl;
    call_tmp_chpl3 = sys_strerror_syserr_str(error_chpl, _ref_tmp__chpl);
    ret_to_arg_ref_tmp__chpl = &call_tmp_chpl4;
    _cast(call_tmp_chpl3, ret_to_arg_ref_tmp__chpl);
    errstr_chpl = call_tmp_chpl4;
    ret_chpl = (path_chpl)->len;
    call_tmp_chpl5 = quote_string_chpl(path_chpl, ret_chpl);
    ret_to_arg_ref_tmp__chpl2 = &call_tmp_chpl6;
    _cast(call_tmp_chpl5, ret_to_arg_ref_tmp__chpl2);
    quotedpath_chpl = call_tmp_chpl6;
    (&this_chpl)->len = INT64(0);
    (&this_chpl)->_size = INT64(0);
    (&this_chpl)->buff = nil;
    (&this_chpl)->owned = UINT8(false);
    (&this_chpl)->locale_id = INT32(0);
    (&this_chpl)->len = INT64(0);
    (&this_chpl)->_size = INT64(0);
    call_tmp_chpl7 = ((c_ptr_uint8_t)(nil));
    (&this_chpl)->buff = call_tmp_chpl7;
    (&this_chpl)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl3 = &wrap_call_tmp_chpl;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl7, UINT8(true), default_arglocale_id_chpl, &this_chpl, ret_to_arg_ref_tmp__chpl3);
    type_tmp_chpl = wrap_call_tmp_chpl;
    ret_to_arg_ref_tmp__chpl4 = &_autoCopy_tmp__chpl;
    chpl___PLUS_(&call_tmp_chpl4, &local__str_literal_375_chpl, ret_to_arg_ref_tmp__chpl4);
    call_tmp_chpl8 = _autoCopy_tmp__chpl;
    ret_to_arg_ref_tmp__chpl5 = &_autoCopy_tmp__chpl2;
    chpl___PLUS_(&_autoCopy_tmp__chpl, msg_chpl, ret_to_arg_ref_tmp__chpl5);
    call_tmp_chpl9 = _autoCopy_tmp__chpl2;
    ret_to_arg_ref_tmp__chpl6 = &_autoCopy_tmp__chpl3;
    chpl___PLUS_(&_autoCopy_tmp__chpl2, &local__str_literal_2329_chpl, ret_to_arg_ref_tmp__chpl6);
    call_tmp_chpl10 = _autoCopy_tmp__chpl3;
    ret_to_arg_ref_tmp__chpl7 = &_autoCopy_tmp__chpl4;
    chpl___PLUS_(&_autoCopy_tmp__chpl3, &call_tmp_chpl6, ret_to_arg_ref_tmp__chpl7);
    call_tmp_chpl11 = _autoCopy_tmp__chpl4;
    ret_to_arg_ref_tmp__chpl8 = &_autoCopy_tmp__chpl5;
    chpl___PLUS_(&_autoCopy_tmp__chpl4, &local__str_literal_2331_chpl, ret_to_arg_ref_tmp__chpl8);
    call_tmp_chpl12 = _autoCopy_tmp__chpl5;
    ret_to_arg_ref_tmp__chpl9 = &_autoCopy_tmp__chpl6;
    _cast3(offset_chpl, ret_to_arg_ref_tmp__chpl9);
    call_tmp_chpl13 = _autoCopy_tmp__chpl6;
    ret_to_arg_ref_tmp__chpl10 = &_autoCopy_tmp__chpl7;
    chpl___PLUS_(&_autoCopy_tmp__chpl5, &_autoCopy_tmp__chpl6, ret_to_arg_ref_tmp__chpl10);
    call_tmp_chpl14 = _autoCopy_tmp__chpl7;
    _ref_tmp__chpl2 = &type_tmp_chpl;
    chpl___ASSIGN_2(_ref_tmp__chpl2, &_autoCopy_tmp__chpl7);
    err_msg_chpl = type_tmp_chpl;
    coerce_tmp_chpl = (&err_msg_chpl)->locale_id;
    call_tmp_chpl15 = (coerce_tmp_chpl != chpl_nodeID);
    if (call_tmp_chpl15) {
      halt(&local__str_literal_306_chpl, INT64(126), INT32(55));
    }
    coerce_tmp_chpl2 = (&err_msg_chpl)->buff;
    call_tmp_chpl16 = ((c_string)(coerce_tmp_chpl2));
    chpl_error(call_tmp_chpl16, INT64(126), INT32(55));
    _ref_tmp__chpl3 = &errstr_chpl;
    chpl___TILDE_string(_ref_tmp__chpl3);
    _ref_tmp__chpl4 = &quotedpath_chpl;
    chpl___TILDE_string(_ref_tmp__chpl4);
    _ref_tmp__chpl5 = &err_msg_chpl;
    chpl___TILDE_string(_ref_tmp__chpl5);
    _ref_tmp__chpl6 = &call_tmp_chpl8;
    chpl___TILDE_string(_ref_tmp__chpl6);
    _ref_tmp__chpl7 = &call_tmp_chpl9;
    chpl___TILDE_string(_ref_tmp__chpl7);
    _ref_tmp__chpl8 = &call_tmp_chpl10;
    chpl___TILDE_string(_ref_tmp__chpl8);
    _ref_tmp__chpl9 = &call_tmp_chpl11;
    chpl___TILDE_string(_ref_tmp__chpl9);
    _ref_tmp__chpl10 = &call_tmp_chpl12;
    chpl___TILDE_string(_ref_tmp__chpl10);
    _ref_tmp__chpl11 = &call_tmp_chpl13;
    chpl___TILDE_string(_ref_tmp__chpl11);
    _ref_tmp__chpl12 = &call_tmp_chpl14;
    chpl___TILDE_string(_ref_tmp__chpl12);
  }
  return;
}

