/* SysCTypes.chpl:1 */
 void chpl__init_SysCTypes(int64_t _ln_chpl, int32_t _fn_chpl) {
  c_string modFormatStr_chpl;
  c_string modStr_chpl;
  _ref_int32_t refIndentLevel_chpl = NULL;
  uint64_t call_tmp_chpl;
  uint64_t call_tmp_chpl2;
  chpl_bool call_tmp_chpl3;
  uint64_t call_tmp_chpl4;
  uint64_t call_tmp_chpl5;
  chpl_bool call_tmp_chpl6;
  uint64_t call_tmp_chpl7;
  uint64_t call_tmp_chpl8;
  chpl_bool call_tmp_chpl9;
  uint64_t call_tmp_chpl10;
  uint64_t call_tmp_chpl11;
  chpl_bool call_tmp_chpl12;
  uint64_t call_tmp_chpl13;
  uint64_t call_tmp_chpl14;
  chpl_bool call_tmp_chpl15;
  uint64_t call_tmp_chpl16;
  uint64_t call_tmp_chpl17;
  chpl_bool call_tmp_chpl18;
  uint64_t call_tmp_chpl19;
  uint64_t call_tmp_chpl20;
  chpl_bool call_tmp_chpl21;
  uint64_t call_tmp_chpl22;
  uint64_t call_tmp_chpl23;
  chpl_bool call_tmp_chpl24;
  uint64_t call_tmp_chpl25;
  uint64_t call_tmp_chpl26;
  chpl_bool call_tmp_chpl27;
  uint64_t call_tmp_chpl28;
  uint64_t call_tmp_chpl29;
  chpl_bool call_tmp_chpl30;
  uint64_t call_tmp_chpl31;
  uint64_t call_tmp_chpl32;
  chpl_bool call_tmp_chpl33;
  uint64_t call_tmp_chpl34;
  uint64_t call_tmp_chpl35;
  chpl_bool call_tmp_chpl36;
  uint64_t call_tmp_chpl37;
  uint64_t call_tmp_chpl38;
  chpl_bool call_tmp_chpl39;
  uint64_t call_tmp_chpl40;
  uint64_t call_tmp_chpl41;
  chpl_bool call_tmp_chpl42;
  uint64_t call_tmp_chpl43;
  uint64_t call_tmp_chpl44;
  chpl_bool call_tmp_chpl45;
  uint64_t call_tmp_chpl46;
  uint64_t call_tmp_chpl47;
  chpl_bool call_tmp_chpl48;
  if (chpl__init_SysCTypes_p) {
    goto _exit_chpl__init_SysCTypes_chpl;
  }
  modFormatStr_chpl = "%*s\n";
  modStr_chpl = "SysCTypes";
  printModuleInit(modFormatStr_chpl, modStr_chpl, INT64(9));
  refIndentLevel_chpl = &moduleInitLevel;
  *(refIndentLevel_chpl) += INT64(1);
  chpl__init_SysCTypes_p = UINT8(true);
  call_tmp_chpl = sizeof(c_int);
  call_tmp_chpl2 = sizeof(int32_t);
  call_tmp_chpl3 = (call_tmp_chpl == call_tmp_chpl2);
  assert_chpl(call_tmp_chpl3);
  call_tmp_chpl4 = sizeof(c_uint);
  call_tmp_chpl5 = sizeof(uint32_t);
  call_tmp_chpl6 = (call_tmp_chpl4 == call_tmp_chpl5);
  assert_chpl(call_tmp_chpl6);
  call_tmp_chpl7 = sizeof(c_long);
  call_tmp_chpl8 = sizeof(int64_t);
  call_tmp_chpl9 = (call_tmp_chpl7 == call_tmp_chpl8);
  assert_chpl(call_tmp_chpl9);
  call_tmp_chpl10 = sizeof(c_ulong);
  call_tmp_chpl11 = sizeof(uint64_t);
  call_tmp_chpl12 = (call_tmp_chpl10 == call_tmp_chpl11);
  assert_chpl(call_tmp_chpl12);
  call_tmp_chpl13 = sizeof(c_longlong);
  call_tmp_chpl14 = sizeof(int64_t);
  call_tmp_chpl15 = (call_tmp_chpl13 == call_tmp_chpl14);
  assert_chpl(call_tmp_chpl15);
  call_tmp_chpl16 = sizeof(c_ulonglong);
  call_tmp_chpl17 = sizeof(uint64_t);
  call_tmp_chpl18 = (call_tmp_chpl16 == call_tmp_chpl17);
  assert_chpl(call_tmp_chpl18);
  call_tmp_chpl19 = sizeof(c_char);
  call_tmp_chpl20 = sizeof(int8_t);
  call_tmp_chpl21 = (call_tmp_chpl19 == call_tmp_chpl20);
  assert_chpl(call_tmp_chpl21);
  call_tmp_chpl22 = sizeof(c_schar);
  call_tmp_chpl23 = sizeof(int8_t);
  call_tmp_chpl24 = (call_tmp_chpl22 == call_tmp_chpl23);
  assert_chpl(call_tmp_chpl24);
  call_tmp_chpl25 = sizeof(c_uchar);
  call_tmp_chpl26 = sizeof(uint8_t);
  call_tmp_chpl27 = (call_tmp_chpl25 == call_tmp_chpl26);
  assert_chpl(call_tmp_chpl27);
  call_tmp_chpl28 = sizeof(c_short);
  call_tmp_chpl29 = sizeof(int16_t);
  call_tmp_chpl30 = (call_tmp_chpl28 == call_tmp_chpl29);
  assert_chpl(call_tmp_chpl30);
  call_tmp_chpl31 = sizeof(c_ushort);
  call_tmp_chpl32 = sizeof(uint16_t);
  call_tmp_chpl33 = (call_tmp_chpl31 == call_tmp_chpl32);
  assert_chpl(call_tmp_chpl33);
  call_tmp_chpl34 = sizeof(c_intptr);
  call_tmp_chpl35 = sizeof(int64_t);
  call_tmp_chpl36 = (call_tmp_chpl34 == call_tmp_chpl35);
  assert_chpl(call_tmp_chpl36);
  call_tmp_chpl37 = sizeof(c_uintptr);
  call_tmp_chpl38 = sizeof(uint64_t);
  call_tmp_chpl39 = (call_tmp_chpl37 == call_tmp_chpl38);
  assert_chpl(call_tmp_chpl39);
  call_tmp_chpl40 = sizeof(c_ptrdiff);
  call_tmp_chpl41 = sizeof(int64_t);
  call_tmp_chpl42 = (call_tmp_chpl40 == call_tmp_chpl41);
  assert_chpl(call_tmp_chpl42);
  call_tmp_chpl43 = sizeof(ssize_t);
  call_tmp_chpl44 = sizeof(int64_t);
  call_tmp_chpl45 = (call_tmp_chpl43 == call_tmp_chpl44);
  assert_chpl(call_tmp_chpl45);
  call_tmp_chpl46 = sizeof(size_t);
  call_tmp_chpl47 = sizeof(uint64_t);
  call_tmp_chpl48 = (call_tmp_chpl46 == call_tmp_chpl47);
  assert_chpl(call_tmp_chpl48);
  *(refIndentLevel_chpl) -= INT64(1);
  _exit_chpl__init_SysCTypes_chpl:;
  return;
}

